version: "3.7"

services:

  flask:
    build: ./app
    container_name: mgsena-flask
    restart: always
    environment:
      - APP_NAME=mgsena-flask
    expose:
      - 5090

  nginx:
    build: ./nginx
    container_name: mgsena-nginx
    restart: always
    ports:
      - "80:80"