version: "3.7"

services:

  flask:
    build: ./app
    container_name: mgsena-flask
    restart: always
    environment:
      - APP_NAME=mgsena-flask
    expose:
      - 5090
  
  flask01:
    build: ./app01
    container_name: mgsena-flask01
    restart: always
    environment:
      - APP_NAME=mgsena-flask
    expose:
      - 5091
  
  nginx:
    build: ./nginx
    container_name: mgsena-nginx
    restart: always
    ports:
      - "80:80"