version: "3.7"

services:
  
  flask01:
    build: ./app01
    container_name: mgsena-flask01
    restart: always
    environment:
      - APP_NAME=mgsena-flask
    expose:
      - 5091
  
  flask02:
    build: ./app02
    container_name: mgsena-flask02
    restart: always
    environment:
      - APP_NAME=mgsena-flask
    expose:
      - 5092
    depends_on: 
      - flask01

  flask03:
    build: ./app03
    container_name: mgsena-flask03
    restart: always
    environment:
      - APP_NAME=mgsena-flask
    expose:
      - 5093
    depends_on: 
      - flask02
  flask04:
    build: ./app04
    container_name: mgsena-flask04
    restart: always
    environment:
      - APP_NAME=mgsena-flask
    expose:
      - 5094
    depends_on: 
      - flask03

  flask05:
    build: ./app05
    container_name: mgsena-flask05
    restart: always
    environment:
      - APP_NAME=mgsena-flask
    expose:
      - 5095
    depends_on: 
      - flask04

  flask06:
    build: ./app06
    container_name: mgsena-flask06
    restart: always
    environment:
      - APP_NAME=mgsena-flask
    expose:
      - 5096
    depends_on: 
      - flask05

  flask07:
    build: ./app07
    container_name: mgsena-flask07
    restart: always
    environment:
      - APP_NAME=mgsena-flask
    expose:
      - 5097
    depends_on: 
      - flask06

  flask08:
    build: ./app08
    container_name: mgsena-flask08
    restart: always
    environment:
      - APP_NAME=mgsena-flask
    expose:
      - 5098
    depends_on: 
      - flask07

  flask09:
    build: ./app09
    container_name: mgsena-flask09
    restart: always
    environment:
      - APP_NAME=mgsena-flask
    expose:
      - 5099
    depends_on: 
      - flask08

  nginx:
    build: ./nginx
    container_name: mgsena-nginx
    restart: always
    ports:
      - "80:80"